### ISSUE TITLE
Please reorganize README

### ISSUE THREAD

**Issue by pcav** [lccanon/Radiotrack#3]
Current top dir README mention a different plugin name from the one published.
The main README apparently resides in the Documentation dir.
I'd suggest to combine the two, and put it in the top dir as md or rst file, so that it can be displayed correctly and compiled as html, pdf etc.
Thanks.

**Comment by lccanon** [comment]
Good idea. Generating the doc automatically from the md is left for future dev (it will be done manually in the mean time). The main README is more complete now.
