### ISSUE TITLE
The date format is not specified

### ISSUE THREAD

**Issue by i-s-o** [lccanon/Radiotrack#4]
The date shown in the example is `23/01/2018 03:48:00`, but it is not clear whether this information will be used internally by the plugin: It would be helpful to indicate its use in the documentation.

Also, if the `date` column is used in internal calculations, switching to ISO format (maybe with a space character between the date and time instead of the strict standard which specifies `T`) would probably save future headaches for many people. E.g.:
`2018-01-23 03:48:00` instead of `23/01/2018 03:48:00`

On a separate note, many software tools would label that column `time` rather than `date` (or `timestamp`, `datetime`, etc.), if it is expected to include the time of the day along with the date.

**Comment by lccanon** [comment]
Updating the documentation is ongoing. The date is used when filtering measures and to detect biangulation, multiple measures for the same individual at the same time.

Allowing other date formats is already possible: there is a combobox in the property tab with the same ISO-like format you mention and a few additional ones.

Thank you for your suggestion to rename date. This will be part of the next version.

**Comment by lccanon** [comment]
Date has been renamed as datetime starting with version 0.6.

Updating the documentation is the last remaining task before closing this issue.

**Comment by lccanon** [comment]
The documentation has been updated.
